### ISSUE TITLE
Joining the new SB community!

### ISSUE THREAD

**Issue by generalwrex** [David-Ralphsky/SBEP-Weapons#2]
Would you like to be part of the new (old) SB community and have your changes merged into the official repository or something along the lines of that ;) We're looking for more sb devs to get it back on its feet! 

https://github.com/SnakeSVx/sbep

Looking forward to see you there if you can make it!

**Comment by DavidRalphsky** [comment]
Neither I (David-Ralphsky), nor X-Coder are actually official Spacebuild devs, and these weapons have been phased out by SB4.
If you mean help work on Spacebuild itself, I'd be glad to help, but I can't say I'm a god-tier coder XD

Add me on Steam: http://www.steamcommunity.com/id/DavidRalphsky/

**Comment by generalwrex** [comment]
:)  anyone can be an sb dev!  He'll I've been a collaborator for it for ye ars, and I'm finally doing stuff =P  

P.s. added you.. [XTT] General Wrex
